### ISSUE TITLE
ionic start issue

### ISSUE THREAD

**Issue by abhilashenair** [driftyco/ionic-site#515]
ionic start todo2 example
module.js:341
    throw err;
    ^

Error: Cannot find module 'archiver'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/utils.js:3:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

**Comment by perrygovier** [comment]
This issue was moved to driftyco/ionic-cli#912
