### ISSUE TITLE
docs: Can't build when offline

### ISSUE THREAD

**Issue by seanmavley** [driftyco/ionic-site#595]
```
khophi:Docs$ gulp watch
[14:03:24] Using gulpfile ~/Developments/Ionic/Docs/Gulpfile.js
[14:03:24] Starting 'ionicons'...
[14:03:25] Finished 'ionicons' after 34 ms
[14:03:25] Starting 'server:ionicons'...
ionicons built
[14:03:25] Finished 'server:ionicons' after 531 μs
[14:03:25] Starting 'styles:v1'...
[14:03:25] Starting 'styles:v2'...
[14:03:25] Starting 'images'...
[14:03:25] Starting 'jekyll-build'...
Configuration file: _config_development.yml
            Source: /home/khophi/Developments/Ionic/Docs
       Destination: /home/khophi/Developments/Ionic/Docs/_site
 Incremental build: enabled
      Generating... 
                    done in 1.305 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
[14:03:28] Finished 'jekyll-build' after 2.96 s
events.js:159
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (Broken @import declaration of "https://fonts.googleapis.com/css?family=Nunito:300" - getaddrinfo EAI_AGAIN fonts.googleapis.com:443)
    at DestroyableTransform.emit (events.js:157:17)
    at onwriteError (/home/khophi/Developments/Ionic/Docs/node_modules/gulp-minify-css/node_modules/readable-stream/lib/_stream_writable.js:250:10)
    at onwrite (/home/khophi/Developments/Ionic/Docs/node_modules/gulp-minify-css/node_modules/readable-stream/lib/_stream_writable.js:268:5)
    at WritableState.onwrite (/home/khophi/Developments/Ionic/Docs/node_modules/gulp-minify-css/node_modules/readable-stream/lib/_stream_writable.js:106:5)
    at afterTransform (/home/khophi/Developments/Ionic/Docs/node_modules/gulp-minify-css/node_modules/readable-stream/lib/_stream_transform.js:104:5)
    at TransformState.afterTransform (/home/khophi/Developments/Ionic/Docs/node_modules/gulp-minify-css/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /home/khophi/Developments/Ionic/Docs/node_modules/gulp-minify-css/index.js:113:9
    at /home/khophi/Developments/Ionic/Docs/node_modules/gulp-minify-css/index.js:36:7
    at whenSourceMapReady (/home/khophi/Developments/Ionic/Docs/node_modules/clean-css/lib/clean.js:89:16)
    at Object.whenDone (/home/khophi/Developments/Ionic/Docs/node_modules/clean-css/lib/clean.js:98:14)
    at processNext (/home/khophi/Developments/Ionic/Docs/node_modules/clean-css/lib/imports/inliner.js:105:13)
    at importFrom (/home/khophi/Developments/Ionic/Docs/node_modules/clean-css/lib/imports/inliner.js:79:10)
    at processNext (/home/khophi/Developments/Ionic/Docs/node_modules/clean-css/lib/imports/inliner.js:104:16)
    at handleError (/home/khophi/Developments/Ionic/Docs/node_modules/clean-css/lib/imports/inliner.js:237:5)
    at ClientRequest.<anonymous> (/home/khophi/Developments/Ionic/Docs/node_modules/clean-css/lib/imports/inliner.js:273:5)
    at emitOne (events.js:90:13)
khophi:Docs$ 

```
Complains of not being able to access an import declaration. 

If can't build locally when offline, then I guess it defeats the whole point of https://github.com/driftyco/ionic-site#local-build

**Comment by seanmavley** [comment]
Commenting out this line:
https://github.com/driftyco/ionic-site/blob/master/_scss/v2.scss#L9

folder gets the build to work when offline.

`// @import url('https://fonts.googleapis.com/css?family=Nunito:300');`

Any way to work around this, such as including the Nunito family icon locally?

**Comment by perrygovier** [comment]
Feel free to comment out the line for your own purposes. The primary purpose of developing locally is to see what your changes look like before publishing them, so requiring the developer be online to build isn't a major concern.

With that said, our primary font, Avenir Next, seems to be loading without issue for all of our users, so the Nunito fallback is unnecessary and I plan on removing it soon.
