### ISSUE TITLE
[v2] TypeError: nextInput.initFocus is not a function

### ISSUE THREAD

**Issue by speciose** [driftyco/ionic-site#606]
When I navigate through the form of my Ionic 2 app with Tab (Chrome Browser) I get this error after last input field:
(after last input field I have checkboxes)

```
EXCEPTION: TypeError: nextInput.initFocus is not a function
browser_adapter.ts:73 EXCEPTION: TypeError: nextInput.initFocus is not a functionBrowserDomAdapter.logError @ browser_adapter.ts:73BrowserDomAdapter.logGroup @ browser_adapter.ts:84ExceptionHandler.call @ exception_handler.ts:49(anonymous function) @ application_ref.ts:258schedulerFn @ async.ts:127SafeSubscriber.__tryOrUnsub @ Subscriber.js:166SafeSubscriber.next @ Subscriber.js:115Subscriber._next @ Subscriber.js:74Subscriber.next @ Subscriber.js:51Subject._finalNext @ Subject.js:124Subject._next @ Subject.js:116Subject.next @ Subject.js:73EventEmitter.emit @ async.ts:113NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:134NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:88ZoneDelegate.handleError @ angular2-polyfills.js:394Zone.runTask @ angular2-polyfills.js:323ZoneTask.invoke @ angular2-polyfills.js:490
browser_adapter.ts:73 STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.ts:73ExceptionHandler.call @ exception_handler.ts:52(anonymous function) @ application_ref.ts:258schedulerFn @ async.ts:127SafeSubscriber.__tryOrUnsub @ Subscriber.js:166SafeSubscriber.next @ Subscriber.js:115Subscriber._next @ Subscriber.js:74Subscriber.next @ Subscriber.js:51Subject._finalNext @ Subject.js:124Subject._next @ Subject.js:116Subject.next @ Subject.js:73EventEmitter.emit @ async.ts:113NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:134NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:88ZoneDelegate.handleError @ angular2-polyfills.js:394Zone.runTask @ angular2-polyfills.js:323ZoneTask.invoke @ angular2-polyfills.js:490
browser_adapter.ts:73 TypeError: nextInput.initFocus is not a function
    at Form.tabFocus (http://localhost:8100/build/js/app.bundle.js:65940:34)
    at http://localhost:8100/build/js/app.bundle.js:44359:33
    at http://localhost:8100/build/js/app.bundle.js:28614:94
    at ZoneDelegate.invokeTask (http://localhost:8100/build/js/angular2-polyfills.js:423:38)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (http://localhost:8100/build/js/app.bundle.js:28433:41)
    at ZoneDelegate.invokeTask (http://localhost:8100/build/js/angular2-polyfills.js:422:43)
    at Zone.runTask (http://localhost:8100/build/js/angular2-polyfills.js:320:48)
    at ZoneTask.invoke (http://localhost:8100/build/js/angular2-polyfills.js:490:34)
  -------------   Elapsed: 17 ms; At: Tue May 17 2016 19:00:03 GMT+0300 (MSK)   -------------  
    at Object.Zone.longStackTraceZoneSpec.onScheduleTask (http://localhost:8100/build/js/angular2-polyfills.js:1413:23)
    at ZoneDelegate.scheduleTask (http://localhost:8100/build/js/angular2-polyfills.js:400:50)
    at Zone.scheduleMacroTask (http://localhost:8100/build/js/angular2-polyfills.js:340:40)
    at http://localhost:8100/build/js/angular2-polyfills.js:189:26
    at setTimeout (eval at createNamedFn (http://localhost:8100/build/js/angular2-polyfills.js:1032:18), <anonymous>:3:37)
    at SafeSubscriber._next (http://localhost:8100/build/js/app.bundle.js:28614:62)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/js/app.bundle.js:94371:16)
    at SafeSubscriber.next (http://localhost:8100/build/js/app.bundle.js:94320:22)BrowserDomAdapter.logError @ browser_adapter.ts:73ExceptionHandler.call @ exception_handler.ts:53(anonymous function) @ application_ref.ts:258schedulerFn @ async.ts:127SafeSubscriber.__tryOrUnsub @ Subscriber.js:166SafeSubscriber.next @ Subscriber.js:115Subscriber._next @ Subscriber.js:74Subscriber.next @ Subscriber.js:51Subject._finalNext @ Subject.js:124Subject._next @ Subject.js:116Subject.next @ Subject.js:73EventEmitter.emit @ async.ts:113NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:134NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:88ZoneDelegate.handleError @ angular2-polyfills.js:394Zone.runTask @ angular2-polyfills.js:323ZoneTask.invoke @ angular2-polyfills.js:490
form.js:63 Uncaught TypeError: nextInput.initFocus is not a function
```

**Comment by mhartington** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the ionic site itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the framework, please open an issue [here](https://github.com/driftyco/ionic/issues/new) and fill out the required information.
